job_products/urls.py
from django.urls import path, include
from . import views
app_name = 'crawler'
urlpatterns = [
    path("",views.news,name='news'),
    path("Job/",views.job,name='job'),
    path("LatestBooks",views.Book_view,name='Book'),
    path("JobCsvFormat/",views.Csv_format,name='Csv_format'),
    path("NewsCsvformat/",views.News_Csv_format,name='News-Csv-format'),
    path("BooksCsvformat/",views.Books_Csv_format,name='Books-Csv-format'),
]

mysite/urls.py
from django.urls import path,include

urlpatterns = [
    path('',include('job_products.urls'))
]

job_products/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    price = models.CharField(max_length=255)
    image = models.URLField(max_length=255)

    def save(self,*args,**kwargs):
        if self.title == self.title:
            self.title = self.title
        return super(Book,self).save(*args,**kwargs)

    def __str__(self) -> str:
        return self.title


class Jobs(models.Model):
    title = models.CharField(max_length=255,blank=True,null=True)
    url = models.URLField(max_length=255,blank=True,null=True)
    company = models.CharField(max_length=255,blank=True,null=True)
    desc = models.TextField(max_length=255,blank=True,null=True)
    country = models.CharField(max_length=255,blank=True,null=True)
    date_posted = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['date_posted']

    def __str__(self) -> str:
        return self.title

class News(models.Model):
    headline = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    image = models.URLField(max_length=255)
    date_posted = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.headline
    def save(self,*args,**kwargs):
        if self.headline == self.headline:
            self.headline = self.headline
        return super(News,self).save(*args,**kwargs)

    class Meta:
        ordering = ['date_posted']
    

job_products/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup
from . models import Book,Jobs,News
from django.http import HttpResponse
import csv

def Csv_format(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="jobs.csv"'},
    )
    jobs_data = Jobs.objects.all()
    writer = csv.writer(response)
    writer.writerow(['Title',"Url",'Company','Country location','looking For',])
    for data in jobs_data:
        writer.writerow([data.title,data.url,data.company,data.country,data.desc])  
    return response

def News_Csv_format(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="News.csv"'},
    )
    News_data = News.objects.all()
    writer = csv.writer(response)
    writer.writerow(['Headlines',"Url",'Image','Date'])
    for data in News_data:
        writer.writerow([data.headline,data.url,data.image,data.date_posted])  
    return response


def Books_Csv_format(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="Books.csv"'},
    )
    Books_data = Book.objects.all()
    writer = csv.writer(response)
    writer.writerow(['Title',"Url",'Price','Image'])
    for data in Books_data:
        writer.writerow([data.title,data.url,data.price,data.image])  
    return response



def index(request):
   
    return render(request,'job_products/base.html',)

def job(request):
    url = 'https://www.python.org/jobs/'
    response = requests.get(url)
    soup = BeautifulSoup(response.content,'lxml')
    job_article = soup.find('ol')
    job_list = job_article.find_all('li')
    for job in job_list:
        job_title = job.find('h2').a.string
        company = job.find('h2').a.next_sibling.next_sibling.strip()
        country = job.find('h2').span.next_sibling.next_sibling.a.string.strip()
        url = job.find('h2').span.next_sibling.next_sibling.a.get('href')
        urls = 'https://www.python.org'+url
        category = job.find('span',class_='listing-job-type').contents
        date_posted = job.find_all('time')
       
        
        job_data = Jobs()
        job_data.title = job_title
        job_data.url = urls
        for cat in category:
            job_data.desc = cat
        job_data.country = country
        job_data.company = company
        job_data.save()

        
    object_list = Jobs.objects.all()[:20]
    return render(request,'job_products/job.html',{'job':object_list})


def news(request):
    url = 'https://www.naijaloaded.com.ng/news'
    response = requests.get(url)
    soup = BeautifulSoup(response.content,'lxml')
    news_article = soup.find_all('article',limit=20)
    try:
        for articles in news_article:
            image = articles.img.get('src')
            url = articles.a.get('href')
            headline = articles.header.h3.a.string
            News_data = News()
            News_data.headline = headline
            News_data.url = url
            News_data.image = image
            News_data.save()
            object_list = News.objects.all()
        if headline and url and image in object_list:
                object_list.delete()
        object_list = News.objects.all()[:20]
    except:
        pass
    
    return render(request,'job_products/news.html',{'object_list':object_list})

def Book_view(request):
    url = 'http://books.toscrape.com/index.html'
    response = requests.get(url)
    soup = BeautifulSoup(response.content,'lxml')
    book_article = soup.find_all('article')
    for books in book_article:
        title = books.h3.a.string.strip()
        url = books.h3.a.get('href')
        images = books.img.get('src')
        price_div = books.div
        price_value = price_div.find_next_sibling('div').contents
        price = price_value[1].string.strip()

        books_data = Book()
        books_data.title = title
        books_data.url = url
        books_data.price = price
        books_data.image = images
        books_data.save()
    
    book_list = Book.objects.all()[:20]  
    return render(request,'job_products/book.html',{'book':book_list})

job_products/templates/job_products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Daily...Thoughts{% endblock title %}</title>
    <link rel="stylesheet" href=" {% static 'job_products/main.css' %}">
    <script src=" {% static 'job_products/main.js' %}"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/18de66c05e.js" crossorigin="anonymous"></script>
</head>
<body>
     <!--- wrapper header-->
    <div class="wrapper">
       <div class="header-menu">
        <div class="logo">Daily...<br> Thoughts<i class="fa-brands fa-neos"></i></div>
    
        <div class="menu">
           <a href="{% url 'crawler:news' %}"> <i class="fa-brands fa-neos"> </i>Latest News Reports </i></a>
           <a href="{% url 'crawler:job' %}">Latest Dev Jobs </i></a>
           <a href="{% url 'crawler:Book' %}">Latest Novel Books</i></a>
    
          
        </div>
        
       </div>
    <!-- end of menu-->
    <div class="content-holder">
{% block content-holder %}


{% endblock content-holder %}
    </div>


    <div class="footer">
        <div>
            <h4>LET US HELP YOU</h4>
            <p>Help Center</p>
            <p>How to get latest Thoughts</p>
            <p>Delivery options and Timelines</p>
            <p>Report a News</p>
            
         </div>
         <div>
             <h4>ABOUT DAILY THOUGHTS</h4> 
            <p>About us</p>
            <p>Terms and Condtions</p>
            <p>Free Digital Product links</p>
            <p>Free Books links </p>
          </div>
         
         
          <div>
             <h4>JOIN US ON</h4> 
             
                 <i class="fa-brands fa-facebook-square"></i>
                 <i class="fa-brands fa-youtube"></i>
                 <i class="fa-brands fa-whatsapp"></i>
                 <i class="fa-brands fa-linkedin"></i>
                 <i class="fa-brands fa-instagram"></i>
                 <br>
          </div>
         
         </div>
         <div class="copyright">
             
            <p>Copyright © 2022 DailyThought.com. All rights reserved</p>
         </div>

    </div>

    </div>
      <!--- wrapper header-->
</body>
</html>

job_products/templates/job_products/book.html
{% extends 'job_products/base.html' %}
{% block title %}Daily...Thoughts | Latest Books{% endblock title %}
{% block content-holder %}
<div class="export-container">
    <div class="data-btn">Export Data: &nbsp; &nbsp;<button><a href="{% url 'crawler:Books-Csv-format' %}">CSV</a></button></div>
</div>
{% if book %}
{% for objects in book %}

<div class="News_content-holder">
    <img src="http://books.toscrape.com/{{objects.image}}">
    <a href="http://books.toscrape.com/{{objects.url}}"><p style="text-align: center; font-size:18px">{{objects.title}}</p></a>
    <br/>
    <p align="center">{{objects.price}}<p/>


</div>
{% endfor %}
{% endif %}
{% endblock content-holder %}

job_products/templates/job_products/job.html
{% extends 'job_products/base.html' %}
{% block title %}Daily...Thoughts | Jobs{% endblock title %}
{% block content-holder %}
<div class="export-container">
    <div class="data-btn">Export Data: &nbsp; &nbsp;<button><a href="{% url 'crawler:Csv_format' %}">CSV</a></button> </div>
</div>
<div class="job-container">
    {% if job %}
    {% for jobs in job %}
<div class="job-content">
    <p style="float:right;">{{jobs.country|truncatewords:'8'}}</p>
    <a href="{{jobs.url}}"><p><span>New</span>&nbsp;&nbsp; {{jobs.title}}</p></a>
    <br>
    <br>
    <p>Company: &nbsp;&nbsp;{{jobs.company}}</p>
    <br>
    <br>
    {% if jobs.desc %}
    <p>Looking for: &nbsp;&nbsp;{{jobs.desc}}</p>
    {% else %}
    {% endif %}
    
    <br>
    <br>
    
</div>
{% endfor %}
{% endif %}
</div>

{% endblock content-holder %}

job_products/templates/job_products/news.html
{% extends 'job_products/base.html' %}
{% block title %}Daily...Thoughts | News{% endblock title %}
{% block content-holder %}
<div class="export-container">
    <div class="data-btn">Export Data: &nbsp; &nbsp;<button><a href="{% url 'crawler:News-Csv-format' %}">CSV</a></button></div>
</div>
{% if object_list %}
{% for objects in object_list  %}
<div class="News_content-holder">
    <img src="{{objects.image}}">
    <a href="{{objects.url}}"><p>{{objects.headline}}</p></a>


</div>
{% endfor %}
{% endif %}
{% endblock content-holder %}